---
pdf-engine: xelatex
number-sections: true
highlight-style: pygments
template: ./latex/template.tex
csl: ./latex/citation.csl
include-in-header: 
  - ./latex/preamble.tex
resource-path: 
  - ./
  - ./markdown
output-file: report.pdf
variables:
  lang: de
  fontsize: 11pt
  documentclass: report
  papersize: a4paper
  classoption: openright
  title: "My awsome Master thesis"
  author: "Julian Ortel"
  date: "06.06.6666"
