---
pdf-engine: xelatex
number-sections: true
highlight-style: pygments
template: ./latex/template.tex
csl: ./latex/citation.csl
resource-path: 
  - ./
  - ./markdown
output-file: thesis.pdf
variables:
  lang: de
  fontsize: 11pt
  documentclass: scrreprt
  papersize: a4paper
  classoption: openright
  # change the following values to your like
  title: "My awsome Master thesis"
  thesis-type: Master's
  author: "Julian Ortel"
  date: "01.02.2034"
  toc: true # Table of contents
  lof: true # List of figures
  lot: true # List of tables
  # add all latex files you want to put before your document
  input-before:
    - latex/titlepage.tex
    #- latex/statement.tex
