---
pdf-engine: xelatex
number-sections: true
highlight-style: pygments
template: ./latex/template.tex
csl: ./latex/citation.csl
include-in-header: 
  - ./latex/preamble.tex
resource-path: 
  - ./
  - ./markdown
output-file: thesis.pdf
variables:
  lang: de
  fontsize: 11pt
  #documentclass: report
  documentclass: scrreprt
  papersize: a4paper
  classoption: openright
  # change these values
  title: "My awsome Master thesis"
  author: "Julian Ortel"
  date: "06.06.6666"
  supervisor_1: "Prof. Dr. Thorsten Holz"
  supervisor_2: "Prof. Dr. Someone Else"
